sudo: required
languages: go
services:
- docker
script:
- DOCKER_GID=999 make
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: Sq67YdxCNdDiHjE+ZxF2f5UmvYi1FJIU1Po9N2f02eJMJFsqCXg+rQbK4b9yp7vTJz5vVB/pfrRWePdBd08WPQHxCRxOK+2oqq9z4Fo6v5TyxTn63fSSgL+EsDvmzzJbR9WCTUIc56SmdtX10p/QYcqZzdxitOd8lvyOMxs3eolr3yrq9oSuuq/xhnS3X8yhCJ3sq/Z9orx8tH6UrmgJJDAyxxbXV7nt8sbOt63v4jGmJgFMOpKPkka1Oimn8KvqUvS51o4hxy163tSTpgv8ij4jRAyiT4Vp5YlNO8RTQZYyfwtmPApuNVEn+/2qQLk2r26I3J7IRdYVvFVHTpNB3YXen3yI/AFFtlavMhhJOAukGf9aGpVgX8ZQnYkyMNv8jhtxIU1a9FJ9PhhkkvHC3EgP9A/zZGu6hlaG7dGvYRelSK8/ftcz3O8hq7T4UW9RB88J0H3/+uIP1V6ORof0I6LF+ZnxXkDb6A8U1oT7HOAxqmsPa+i2u8sqYsnuR1tmDmcauOkTAMd/Q5wRsttOe4OciDrIZQ+znYrtTVvbac4k/gyI+ruSzyQhvTxUnAGEgVVMLHbtTHo/t8JSmQppQvgKeizuYL/WUo3KPNR1eDSX2U9+W0Xm+T0hxaIQYXPgYD47ykRom2bKxqg84JPiIL0pgRtLfPBicoLndlz8kN0=
  - secure: AqJE20fp3tXnFgETxvjSZFWj0MtF/3+Xg3W9UJLpxaLh1ej56yHZ2D0khwYo+3vQHxE8Vik+UIfWfs9+9CA7NBpUMT6/siHGURsYQOa47zw8Bmpjj+nP+Z8tDykvzKvxsDW9iA3xnjH+NMMdlkiqha6Ae/lhQ30U7TumwKKugB8AmRo9L/FsiF6YvFqQDOuvrJTvoYNwk/90Eei+2dxkO8vrvvqYloDEW/eGbm+oQ5WXoM955UcMDxcvFJOF7VQHNlKmb2n7Qckxd2s8Se5TfVWC8ngCutvQt/wEX4YEQ++aksmzZ3gBKUuaJFMOkUbcuhUBVke6d1rn6fQ80AlPCDwgiofCcoFPwxkFNZXWdvLBGrQFkM+0VYCB8bChIdmZ+LtZQ6+oqf6Z16uJQG6wAUNzeZJNKDAGIMPqOg1NfrM3KG6rEL/IJ0ADGSkNsjhV3PA8ApEreBRKYt1kuB4CDgLMQFGwjEYW2XRg6iwCqUFLEFKnSPZXMA5YbfLsNFMWrnkCis2aaLNAyp88vNLs+imo+RioLqlchBPd4Wl9yi8zbAfPFKLF8g3q9FajlOKx/KAz000JGrGF0nRiiURBN+xclsPcHIvSmIoBK17sgDq8U2jnhzZEEvYD9c0N4xVrkDtyIqvR687NW6jKK39O5d4L0lzD9SAT4IotAHxZhwU=
after_success:
- echo "DOCKER_USER [" $DOCKER_USER "] DOCKER PASS [" $DOCKER_PASS "]"
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=tomgeorge/devbox
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker tag devbox $REPO:$TAG
- docker tag devbox $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO:$TAG
