sudo: required
languages: go
services:
- docker
script:
- DOCKER_GID=999 make
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
DOCKER_EMAIL:
  secure: ix18yz0/mHUMmeqccIgMgQ6bOGQCHG5QI3/JK/FN5rJcyh7THOO4XPMZjiPqCgI/p1ribPWOa2+UKpx0QDtVF2WGdGkYFXaBQfd5uR9W7RDJl2RwxQ3ofoywdmTdLBa4B6/OAd+d2NUB0bK71k55LdYAlFYF1YVf2LKlT/TnwtDg3GJDs0Xeojzy0O2Tl9+2EAqWZQlFW+DKgsrbzfQfr3KP1rGkNz77QIR7ycBZQZN8lZNDNzQsDJAHwbiuqERcZMgBvev1DFoICm0zvRXlKZhRG5YzgW2R6h+zBf7UxZbHruACNxIixS7kx4RQpv5Cok+hHHA3/+CXfC6Kx3MiPZPtYtctAAVkHDkCrGMtHFbpRS+PNhbPUkY8qwHcO7tg0rp8RJ2lJvFuXOvtqTsbxEmRYAnMXCSlKzVHA8SKrjY/DE+aC15ScuKwaa3L0m3mp//LNMzGrImtyTiXZz2MDk9BSQwq64iPaCGanFCkwUZJtR6jxk1qf1DOCSXnyF7DXaUaw32b+FfT6MgIhluzux/or4U+iJC30zvd7NVYIfmawVeE0FQT+xgTYzqCM5pk82RZgU6pC7wOUqt5FPr8wIDK3bPNGKY99JbXLYdclWJDZqQemDog+x5UeB0bZTlql2MZfAgfQbQXjFGxtY3mguowxE2GfenKA+YvBs/rESY=
DOCKER_USER:
  secure: jtGSocrN7QkGaWazUTvL3dsbcVfFFM2IYaxrGto9RM/KhpEDcJ8aJgVD2h0H3ocEqscqOsjkClRG/Uh/RVAyfbWTRWMzWsEew5+kQ5o3xNsX7J+L+QkcbxOVxLfb6j51T35s89A9B84Rh6JG2CrjqNwH9CDr7g4PF0tC8+seilYK2yrCzvjXQUNKRZvBpOH4PHRv8bY8rJIGTT/EljWv+UE1r81BRq5X5AEUz0KSq9YfrXwi2Q+mlzusXOuQM7U3oecvtajtloIldhVIKajacy3a++rOhO8QPvcVnVaSYJrony2bOWIFzd0si2uDpcs7G6tZmiy4fHQk6eXjnAELqpBeOb9zep0vhPdqelMMCxVWZHW73hfbmlqSrwJ1lGudhIApHzqCla1lzHsTn9OLBDTr4pIBxzOJcIu8Lz4qNfe+EeWyeZ4joMwk5hwLNWyuAKK013aIEyNuTufUC1wk7X/priuK2qQsYC6c+U0TmTXNN+151vfxJmpgSxIj5p0MmBxPwEIMrpZbF6cNRjKHglvjhB+oImKA0FUotbDG47MR02GnmgLxwpVmTSKfScE73B9azcbKyLAZXYlciZP9g9VPEOAtLezXBBfLa+SH/J7g6zxfQ+NDexVMjl8AJjvx8j41AazxClUXwBfE7JsNe7PTgOoJpCpTQlsN/7ZZHcY=
DOCKER_PASS:
  secure: gGBlWKGknbQz2pKECGmpXik6ie/KcBEn9c7UOnAajAeiCmpnNP1PuJzRbZNjd3c54XT1Ct6IhlwFZ7X5ZkymrDfrLXXV98L3RuelD16fWYxfSV6COKLe9dcV5z2ame3xHqIqUQnlnCNbN0KlxqVxcToXEaGI7knGUHoD0BaWhT0Y20d+uG70f/cQ7ob1fNaShzYdMc7JVee5NyD/WJ0YW0m7oa7wCSYwE/e+iCJ3Lhr9oGjExHF1fvsChrAwEjXdC8T34KrlNDh9CDvylNsZdN9M07xRFwHC6TK1lgESj/CChdGixM1hj6EkL4RqafTHqKj5udkmBCJCpzPpfoL6CrtYQVg0XF0GDSbxLnG7usZUOEIfYMZpQt7Awkpo3ypO+OAeFkHxV3JNTtePh3QvztPVfTc8Rr3vjX/hnumura0VCeI0Ha2WVb9jF25pNxswDxCZigOZwylQXG10Fb/1IhJr/feMI04BylWpQaZ2LgwnfLMnQMDhTp+2HdqyMdw2yDuvBUXDPv+iGRwDjt/brDY3JkllIxnqjEyTe6Q1yk56JefcBoPCk2LJXzdkw8xWv+pFmkbbKKWKBgaKHUxFB1vP4t/sFJtmlEbwFd5xe7vK7fZkvX2soHRT6xfkpu7ybz4yoH4Z7DXBySANUh+zoH1Ei1RjjOg1kBHcY/S5gzw=
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=tomgeorge/devbox
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag devbox $REPO:$TAG
  - docker tag devbox $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO:$TAG
